#!/bin/bash

if [ -z $1 ] || [ -z $2 ] ; then
    printf "usage: ./run_knights_tour rows cols\n"
    exit
fi

if [ $1 -eq 2 ] || [ $1 -eq 3 ] || [ $1 -eq 4 ] ; then
    printf "no possible knights tours\n"
fi

for run in {1..100}; do
    python knightstour4.py $1 $2 10000000
done
